# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(blank=True, upload_to=registration.models.avatar_upload_path),
        ),
    ]
